### ISSUE TITLE
No process runs on PORT 8080, yet error!

### ISSUE THREAD

**Issue by uts9009** [sophron/wifiphisher#129] opened 2015-08-11 11:20 UTC
[-] Unable to start HTTP server!
[-] Another process is running on port 8080

**Comment by eranvak** [comment] 2015-08-12 20:02
Yea me too

**Comment by sophron** [comment] 2015-08-13 03:16
Please upload to the latest revision, run the script and paste the output here. I haven't fixed the error as I can't reproduce it yet, but I pushed a commit that will give a more detailed output.

**Comment by countrymanboz** [comment] 2015-08-13 19:54
I'm getting the same problem with Kali 2.0.  A fix would be great! Cheers.

**Comment by Skyprus** [comment] 2015-08-14 07:39
same here

**Comment by countrymanboz** [comment] 2015-08-14 08:10
This is the output, in case it helps?

[-] Unable to start HTTP server (socket errno 99)!
[-] Maybe another process is running on port 8080?
[!] Closing

**Comment by countrymanboz** [comment] 2015-08-14 12:05
set wlan0 to the correct static IP (10.0.0.1) and and all is working now.  Pretty obvious! sorry to have troubled you!

**Comment by uts9009** [comment] 2015-08-15 06:51
[-] Unable to start HTTP server (socket errno 99)!
[-] Maybe another process is running on port 8080?
[!] Closing

this error is coming how to solve it???

**Comment by alisharte** [comment] 2015-08-16 02:31
mee too in kali 
[-] Unable to start HTTP server (socket errno 99)!
[-] Maybe another process is running on port 8080?
[!] Closing

**Comment by mohamed554** [comment] 2015-08-16 02:54
[+] Choose the [num] of the AP you wish to copy: 1
[*] Starting the fake access point...
SIOCADDRT: Network is unreachable
[3;J







[*] MAHMOUD set up on channel 3 via wlan0 on False

[-] Unable to start HTTP server (socket errno 99)!
[-] Maybe another process is running on port 8080?
[!] Closing

**Comment by sophron** [comment] 2015-08-16 05:58
My guess is that for some reason the script is not setting the IP address properly, hence the web server fails to bind. Please update to the latest revision and post the new output here. This will help me track the bug.

Don't forget that you can always use our <a href="https://github.com/sophron/wifiphisher/releases/tag/v1.1">stable release</a>.

**Comment by mohamed554** [comment] 2015-08-16 20:58
mohamed@mohamed-K55A:~/Desktop/TOOLS/wifiphisher-master$ sudo python wifiphisher.py               _  __ _       _     _     _               
              (_)/ _(_)     | |   (_)   | |              
     __      ___| |_ _ _ __ | |__  _ ___| |__   ___ _ __ 
     \ \ /\ / / |  _| | '_ \| '_ \| / __| '_ \ / _ \ '__|
      \ V  V /| | | | | |_) | | | | \__ \ | | |  __/ |   
       \_/\_/ |_|_| |_| .__/|_| |_|_|___/_| |_|\___|_|   
                      | |                                
                      |_|                                
                                                         
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "wifiphisher.py", line 945, in <module>
    sniffing(mon_iface, targeting_cb)
  File "wifiphisher.py", line 415, in sniffing
    sniff(iface=interface, prn=cb, store=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 561, in sniff
    s = L2socket(type=ETH_P_ALL, *arg, **karg)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 455, in __init__
    self.ins.bind((iface, type))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 19] No such device
mohamed@mohamed-K55A:~/Desktop/TOOLS/wifiphisher-master$

**Comment by uts9009** [comment] 2015-08-17 13:08
error solved make your ip static to wlan0 10.0.0.1

**Comment by mohamed554** [comment] 2015-08-18 00:11
how to do it cause i messed up my /etc/network/interfaces

**Comment by blackHatMonkey** [comment] 2016-04-10 20:20
The issue should be solved now. If you still experience any issues after upgrading to the latest version feel free to open a new issue.

**Closed by blackHatMonkey** 2016-04-10 20:20 UTC
Labels: bug
