### ISSUE TITLE
Error on closing

### ISSUE THREAD

**Issue by naflan121** [sophron/wifiphisher#242] opened 2016-04-15 17:29 UTC
Hi @blackHatMonkey  @sophron 

I discover something, when the evil ap started and victim type the password, the attack end with throwing a error . Hope can fix with the coming update 
![1](https://cloud.githubusercontent.com/assets/11876070/14569644/965e68d6-0372-11e6-85c9-78ba4d3e39fb.PNG)
![2](https://cloud.githubusercontent.com/assets/11876070/14569645/9673fcfa-0372-11e6-9fe3-e5c970bbef37.PNG)

**Comment by blackHatMonkey** [comment] 2016-04-16 12:59
The jamming part of the tool is run in a separate thread and what happens here is that it exists ungracefully. This shouldn't impact performance in any way but requires a redesign to that section which is planned.

**Comment by blackHatMonkey** [comment] 2016-06-21 12:27
@sophron It seems that the problem is not fully solved.
```
[*] Starting Wifiphisher 1.1GIT at 2016-06-21 08:24
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wlan1 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "bin/wifiphisher", line 12, in <module>
    run()
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 934, in run
    sniffing(mon_iface, targeting_cb)
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 222, in sniffing
    sniff(iface=interface, prn=cb, store=0, stop_filter=stopfilter)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 570, in sniff
    s = L2socket(type=ETH_P_ALL, *arg, **karg)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 484, in __init__
    _flush_fd(self.ins)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 303, in _flush_fd
    os.read(fd,MTU)
OSError: [Errno 100] Network is down
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 198, in channel_hop
  File "/usr/lib/python2.7/subprocess.py", line 657, in __init__
  File "/usr/lib/python2.7/subprocess.py", line 463, in _cleanup
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'remove'
```

**Comment by sophron** [comment] 2016-11-01 16:50
I'm closing this. We should indeed catch all exceptions (not only those on closing) but this is not urgent for the upcoming release.

**Closed by sophron** 2016-11-01 16:50 UTC
Labels: bug
