### ISSUE TITLE
Error After i got Key

### ISSUE THREAD

**Issue by mehranexpert** [sophron/wifiphisher#248] opened 2016-04-22 05:36 UTC
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/Desktop/git/wifiphisher/wifiphisher/pywifiphisher.py", line 674, in sniff_dot11
    sniff(iface=mon_iface, store=0, prn=cb)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 577, in sniff
    p = s.recv(MTU)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 485, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
error: [Errno 100] Network is down

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/Desktop/git/wifiphisher/wifiphisher/pywifiphisher.py", line 447, in channel_hop2
    deauth(monchannel)
  File "/root/Desktop/git/wifiphisher/wifiphisher/pywifiphisher.py", line 505, in deauth
    send(p, inter=float(args.timeinterval), count=int(args.packets))
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 251, in send
    __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose, realtime=realtime)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 234, in __gen_send
    s.send(p)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 389, in send
    self.outs.sendto(sx, sdto)
error: [Errno 100] Network is down

[!] Closing

**Comment by blackHatMonkey** [comment] 2016-04-22 12:14
This is a duplicate of #242 . Please use the same thread for discussing the issue.

**Closed by blackHatMonkey** 2016-04-22 12:14 UTC
