### ISSUE TITLE
Router web page only loads for iphone and not pc

### ISSUE THREAD

**Issue by erawtfos78** [sophron/wifiphisher#255] opened 2016-04-30 23:01 UTC
**Version:**
commit 50cf3a4b6042ce767389488609da03c6f38a02be

**Distribution:**
Have tried Kali 1.1, 2.0 and 1.2016 rolling.  AWUS036H TPLINK WN2772N
**Description:**
Able to initiate deauth on target, however failure in the process to move clients to web page.  Not sure the issue is in the twin ap or in the web page script.  Able to get to via iphone but not pc.

**Steps to Reproduce:**
Launch Wifiphisher, Target AP, Appears it is deauthing, however I am still able to get to web pages on pc.  Only iphone gets re-directed to twin ap.  

**Expected VS actual behavior:**
Have tried a few weeks.  Unsuccessful.  
**Script output:**
Upon cancellation:

^CTraceback (most recent call last):
  File "/root/wifiphisher/bin/wifiphisher", line 12, in <module>
    run()
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 957, in run
    shutdown(used_interfaces)
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 153, in shutdown
    network_manager.set_interface_mode(interface, "managed")
  File "/root/wifiphisher/wifiphisher/interfaces.py", line 475, in set_interface_mode
    self._ifconfig_cmd([interface, "up"])
  File "/root/wifiphisher/wifiphisher/interfaces.py", line 412, in _ifconfig_cmd
    output = command.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 799, in communicate
    return self._communicate(input)
  File "/usr/lib/python2.7/subprocess.py", line 1409, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/usr/lib/python2.7/subprocess.py", line 1463, in _communicate_with_poll
    ready = poller.poll()
KeyboardInterrupt

**Comment by blackHatMonkey** [comment] 2016-04-30 23:16
@erawtfos78 
Please update your OP with the more information.

**Comment by blackHatMonkey** [comment] 2016-05-05 16:31
This seems to be a duplicate of #247. Please continue the discussion there.

**Closed by blackHatMonkey** 2016-05-05 16:31 UTC
