### ISSUE TITLE
Error on Python2.7 (Ubuntu 15.04)

### ISSUE THREAD

**Issue by owais** [sophron/wifiphisher#7] opened 2015-01-04 19:32 UTC
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wifiphisher.py", line 306, in channel_hop
    with lock:
NameError: global name 'lock' is not defined
```

**Comment by scottydelta** [comment] 2015-01-05 09:17
Facing the same issue.

**Comment by timelf123** [comment] 2015-01-05 15:18
```import threading
lock = threading.Lock()```
Just a guess without looking at the code

**Comment by yasoob** [comment] 2015-01-05 17:00
@timelf123 lock is defined in the source code. The problem is that it was defined after it was used in the thread. It should have been defined earlier in the code. Before the thread starts. I have made a pull request which will hopefully close this issue.

**Closed** 2015-01-06 16:16 UTC
