### ISSUE TITLE
error while run wifiphisher - Raspberipi3

### ISSUE THREAD

**Issue by mehranexpert** [sophron/wifiphisher#301] opened 2016-06-27 07:10 UTC
```
root@kali:~# cd /opt/wifiphisher/bin/
root@kali:/opt/wifiphisher/bin# ./wifiphisher -aI wlan2 -jI wlan1
[*] Starting Wifiphisher 1.1GIT at 2016-06-27 07:23
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan2 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "./wifiphisher", line 12, in <module>
    
  File "/opt/wifiphisher/wifiphisher/pywifiphisher.py", line 920, in run
    sniffing(mon_iface, targeting_cb)
  File "/opt/wifiphisher/wifiphisher/pywifiphisher.py", line 209, in sniffing
    sniff(iface=interface, prn=cb, store=0, stop_filter=stopfilter)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 570, in sniff
    s = L2socket(type=ETH_P_ALL, *arg, **karg)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 484, in __init__
    _flush_fd(self.ins)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 303, in _flush_fd
    os.read(fd,MTU)
OSError: [Errno 100] Network is down
root@kali:/opt/wifiphisher/bin# 

```

**Comment by blackHatMonkey** [comment] 2016-06-27 11:44
Hi @mehranexpert 
This is a duplicate of #280 and it's currently being worked on.

**Closed by blackHatMonkey** 2016-06-27 11:44 UTC
