### ISSUE TITLE
help finding 2 wireless network

### ISSUE THREAD

**Issue by noobjo** [sophron/wifiphisher#172] opened 2015-11-10 07:02 UTC
can i use Alfa AWUS036NHA and Alfa AWUS036H and how to turn off my laptop wireless network

**Comment by frafrichile** [comment] 2015-12-07 23:19
I have those two as well but I believe one of them does not support injection. if someone can let me know which one should I purchase. That would be great.

**Comment by blackHatMonkey** [comment] 2015-12-09 18:56
@frafrichile @noobjo 

Two cards that I have confirmed working are ```AWUS036H``` and ```AWUS036NHA```.

**Comment by frafrichile** [comment] 2015-12-09 18:59
@blackHatMonkey  I have those same exact two. Maybe I need to specify which one to use. Do you do that? if so which one do you specify to use.

Thanks!

**Comment by blackHatMonkey** [comment] 2015-12-09 19:01
Please see #180 the workaround post.

**Comment by sophron** [comment] 2015-12-22 22:42
There are some problems with some versions of Alfa at the moment. We believe it's something that has to do with `hostapd`. I'm closing this issue, since it has been reported multiple times.

**Closed by sophron** 2015-12-22 22:42 UTC
