### ISSUE TITLE
Redirect it's ok only with www.google.it

### ISSUE THREAD

**Issue by tonynumero10** [sophron/wifiphisher#193] opened 2016-01-02 23:25 UTC
Hello!!! I have two usb wifi Atheros (AR9485 and AR9271), wifiphisher works good, fake AP is ok, if victim goes on www.google.it opens (very slow) the page to enter the wpa/wpa2, but victim goes on another page wifiphisher don't work!
Why?
And why so very slow?
Thanks for help, and I'm very sorry for my english.

**Comment by blackHatMonkey** [comment] 2016-01-02 23:31
This seems to be a duplicate of #192.

**Comment by sophron** [comment] 2016-01-04 01:06
Indeed it is. Please keep the conversation there.

**Closed by sophron** 2016-01-04 01:06 UTC
