### ISSUE TITLE
Error on Interface

### ISSUE THREAD

**Issue by gbtminhtri** [sophron/wifiphisher#265] opened 2016-05-19 04:22 UTC
I have a problem with my interface:
Traceback (most recent call last):
  File "wifiphisher", line 12, in <module>
    
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 786, in run
    args.apinterface)
  File "/root/wifiphisher/wifiphisher/interfaces.py", line 319, in __init__
    self._check_compatibility(interface_object)
  File "/root/wifiphisher/wifiphisher/interfaces.py", line 444, in _check_compatibility
    device_info = self._iw_cmd([physical_name, "info"]).split("\n")
UnboundLocalError: local variable 'physical_name' referenced before assignment
*****************************************************************************************************
I use Kali linux 2016.1 and usb wireless TL-WN725N

**Comment by sophron** [comment] 2016-05-19 17:12
Hi @gbtminhtri,

It looks like the script fails to retrieve the physical name for the network card. We are currently transitioning to a different library for netlink operations. This should be fixed in the next days.

**Comment by blackHatMonkey** [comment] 2016-05-19 17:34
@gbtminhtri 
What version of `wifiphisher` are you using.
@sophron 
This seems like a duplicate of #235.

**Comment by gbtminhtri** [comment] 2016-05-20 14:15
Hi @sophron.  Thank you. Hope to see this should be fixed soon

**Comment by gbtminhtri** [comment] 2016-05-20 14:20
hi @blackHatMonkey, I am using the latest version of wifiphisher. I fail to start wifiphisher.

**Comment by blackHatMonkey** [comment] 2016-05-20 14:25
@gbtminhtri 
If you have cloned `wifiphisher` can you run the following command:
```bash
git show | grep commit
```
and if not can you clone the latest and see if the problem is still present.

**Comment by bloodymagz** [comment] 2016-05-28 00:13
I have same bug, on the backbox i got this problem too, i think the backbox cant use this, cause of that I tried to install kali linux sana, and i got same problem @sophron sorry for bad english

**Comment by FoRTu** [comment] 2016-05-30 09:12
I have same problem on Raspberry Pi (raspbian). I have 2 USB wireless interfaces connected to the raspberry pi and running `sudo python bin/wifiphisher.py` I get the same error.  I try to clone it again, removing any version downloaded before, but i get the same error.

**Comment by sophron** [comment] 2016-05-30 09:18
Hi guys, 

we should have this solved as soon as we merge #262.

**Comment by sophron** [comment] 2016-07-14 19:55
This should be fixed. Feel free to re-open if you still encounter issues.

**Closed by sophron** 2016-07-14 19:55 UTC
Labels: bug
