### ISSUE TITLE
Failed to start the fake access point! (hostapd error).

### ISSUE THREAD

**Issue by skordonis** [sophron/wifiphisher#292] opened 2016-06-19 16:56 UTC
Working on a Raspberry Pi with raspbian and 2x usb wireless cards( Ralink 5370 chipset)
I had a perfect installation with no issues at all! The process runs smoothly until the program tries to start the fake access point and get the error "Failed to start the fake access point! (hostapd error)".
I tried switching the role of each card using -jI and -aI but i get the same message. 
I wiped the entire installation and started from the beginning but i got the same result. Any ideas?

**Comment by sophron** [comment] 2016-06-19 17:21
Thanks for reporting @skordonis. Do you remember the commit that used to work properly for you?

**Comment by skordonis** [comment] 2016-06-19 17:28
On the raspberry Pi is the first time that i tried to work with wifiphisher, Although i worked before on a Kali Linux machine (with the same usb wifi cards) with no problem arround the time of March 2016. Hope that helps!

**Comment by sophron** [comment] 2016-06-19 17:32
Can you do `hostapd -v` on the raspberry Pi and paste the output here?

**Comment by skordonis** [comment] 2016-06-19 17:36
`root@raspberrypi:~# hostapd -v
hostapd v2.3
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2014, Jouni Malinen <j@w1.fi> and contributors
`

**Comment by bradnie** [comment] 2016-06-20 01:52
Hi Skordonis,
Would you so kind and let me know the make and model of the new wifi card you have ordered.Trying to see what is the latest and greatest model to use for packet injection.Thanx inadvance

**Comment by skordonis** [comment] 2016-06-20 10:45
EDISION WIFI 150 MBPS EDI-MEGA USB ADAPTER IEEE802.11b/g/n
Chipset: Ralink 5370
Encryption: 64/128-Bit WEP, WPS, WPA-PSK, WPA2-PSK
 Hope that helps

**Comment by skordonis** [comment] 2016-06-21 12:16
UPDATE:
So the two new WiFi cards came and they work as they should but an other problem came up. As the program runs with the fake access point broadcasting successfully and wait for a client connection, no client is able to connect to the rogue access point. I tried an android phone, a laptop. I manually try to connect to the rogue AP but keeps dropping the connection. The program runs smoothly though. 
P.S 
Both Raspberry Pi and Kali Linux machine this time.

**Comment by blackHatMonkey** [comment] 2016-06-21 12:18
Hi @skordonis 
Are you able to obtain an IP address or not?

**Comment by skordonis** [comment] 2016-06-21 12:20
@blackHatMonkey 
No IP is assigned to any device. The devices try to connect to the AP but before the "Authenticate" the connection is dropped. Is like the deauth attack is being deployed to the rogue AP and no device can connect to it. (The deauth attack is successful to the correct AP not the rogue one)

**Comment by blackHatMonkey** [comment] 2016-06-21 12:23
I think the problem is with the `DHCP`. Maybe @sophron can help with that.

**Comment by sophron** [comment] 2016-06-27 20:10
Hi @skordonis,

Are you running the latest revision? What `git show | grep commit` says?

What you describe is common when the AP fails to assign an IP address to the connected client. Can you post the output of `ifconfig` when the script is running?

Sorry for the late response. Things were pretty busy here.

**Comment by ammarkhder** [comment] 2016-09-17 11:59
can someone show me who to work with last version of wifiphisher ..its different form the other version

**Comment by Ie0h** [comment] 2016-11-23 17:00
Make sure you don't have any invalid characters in your AP name that you are creating. UNICODE will not work as it will give you that same error.

**Comment by sophron** [comment] 2016-12-07 19:46
I'm closing this. @skordonis feel free to re-open if you still encounter issues.

**Closed by sophron** 2016-12-07 19:46 UTC
