### ISSUE TITLE
Wifiphisher down

### ISSUE THREAD

**Issue by freeroute** [sophron/wifiphisher#296] opened 2016-06-20 08:27 UTC
Hello,
What is the solution for this problem? Wifiphisher installed yesterday. (earlier versions worked correctly)
OS: Kali Rolling Edition
python --version: Python 2.7.11+

airmon-ng: phy0	wlan0		b43		non-mac80211 device? (report this!)
phy1	wlan1		ath9k_htc	Atheros Communications, Inc. TP-Link TL-WN322G v3 / TL-WN422G v2 802.11g [Atheros AR9271]

root@kali:/usr/local/src/wifiphisher# wifiphisher
[*] Starting Wifiphisher 1.1GIT at 2016-06-20 12:16
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.1', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/pywifiphisher.py", line 920, in run
    sniffing(mon_iface, targeting_cb)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/pywifiphisher.py", line 209, in sniffing
    sniff(iface=interface, prn=cb, store=0, stop_filter=stopfilter)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 570, in sniff
    s = L2socket(type=ETH_P_ALL, *arg, **karg)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 484, in __init__
    _flush_fd(self.ins)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 303, in _flush_fd
    os.read(fd,MTU)
OSError: [Errno 100] Network is down

**Comment by blackHatMonkey** [comment] 2016-06-24 14:52
Hi @freeroute 
This is a duplicate of #280. This issue is currently being worked on.

**Closed by blackHatMonkey** 2016-06-24 14:52 UTC
