### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by texnoid** [sophron/wifiphisher#199] opened 2016-01-24 08:25 UTC
Linux raspberrypi 4.1.13-v7+
Raspbian GNU/Linux 8 \n \l
Python 2.7.9

*1. device*
>148f:7601 Ralink Technology, Corp. 
>Device Descriptor:
 > bLength                18
 > bDescriptorType         1
 > bcdUSB               2.01
 > bDeviceClass            0 (Defined at Interface level)
 > bDeviceSubClass         0 
 > bDeviceProtocol         0 
 > bMaxPacketSize0        64
  >idVendor           0x148f Ralink Technology, Corp.
  >idProduct          0x7601 
  >bcdDevice            0.00
  >iManufacturer           1 MediaTek
  >iProduct                2 802.11 n WLAN
  >iSerial                 3 1.0
  >bNumConfigurations      1

*2. device*
  >ID 0b05:17ab ASUSTek Computer, Inc. USB-N13 802.11n Network Adapter (rev. B1) [Realtek   >RTL8192CU]
  >Device Descriptor:
   > bLength                18
    >bDescriptorType         1
    >bcdUSB               2.00
    >bDeviceClass            0 (Defined at Interface level)
    >bDeviceSubClass         0 
    >bDeviceProtocol         0 
    >bMaxPacketSize0        64
    >idVendor           0x0b05 ASUSTek Computer, Inc.
    >idProduct          0x17ab USB-N13 802.11n Network Adapter (rev. B1) [Realtek RTL8192CU]
    >bcdDevice            2.00
    >iManufacturer           1 Realtek
    >iProduct                2 802.11n WLAN Adapter
    >iSerial                 3 00e04c000001
    >bNumConfigurations      1

  *_python wifiphisher.py_*

>[+] Choose the [num] of the AP you wish to copy: 4
>[*] Starting the fake access point...
>Traceback (most recent call last):
>  File "wifiphisher.py", line 984, in <module>
>    if not dhcp(dhcpconf, ap_iface):
>  File "wifiphisher.py", line 510, in dhcp
>    dhcp = Popen(['dnsmasq', '-C', dhcpconf], stdout=PIPE, stderr=DN)
>  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
>    errread, errwrite)
>  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
>    raise child_exception
>OSError: [Errno 2] No such file or directory

**Comment by blackHatMonkey** [comment] 2016-01-24 15:55
This is a duplicate of #194. You need to install ```dnsmasq```and you can find all the details in #194.

**Closed** 2016-01-24 15:57 UTC
Labels: duplicate
