### ISSUE TITLE
Duplicate of #280

### ISSUE THREAD

**Issue by MedoxR** [sophron/wifiphisher#295] opened 2016-06-19 22:41 UTC
Hello everybody,
After typing wifiphisher on terminal I got this lines but no list of access points

[*]Starting wifinisher 1.1GIT at..
[+]Selecting wlan2 interface for the deauthentication attack
[+]Selecting wlan2 interface for creating the rogue acces point
[*]Cleared leases, started DHCP, set up iptables

Anyone have faced the same problem already ?

**Comment by blackHatMonkey** [comment] 2016-06-19 22:43
Hi @MedoxR 
This seems to be a duplicate of #280.

**Comment by abilify01** [comment] 2016-06-20 01:45
I am getting the same problem, mine locks up after choose the number of ap
wifiphisher 
[*] Starting Wifiphisher 1.1GIT at 2016-06-19 21:34
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wlan1 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables

[+] Choose the [num] of the AP you wish to copy: 
 
When I hit ctr-c wifiphisher closes with an error
Traceback (most recent call last):
  File "./wifiphisher", line 12, in <module>    
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 921, in run
    channel, essid, ap_mac = copy_AP()
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 273, in copy_AP
    '] of the AP you wish to copy: ')
KeyboardInterrupt

**Comment by blackHatMonkey** [comment] 2016-06-20 12:13
@abilify01 @MedoxR 
Let's continue the discussion in #280.

**Closed by blackHatMonkey** 2016-06-20 12:13 UTC
Labels: bug, duplicate, solved
